// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

module go.opentelemetry.io/collector/cmd/builder

go 1.18

require (
	go.opentelemetry.io/collector v0.60.0
	go.opentelemetry.io/collector v0.60.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.60.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.60.0
	go.opentelemetry.io/collector v0.60.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.60.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/vaultkvreceiver v0.60.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/journaldreceiver v0.60.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.60.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.60.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusexecreceiver v0.60.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.60.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver v0.60.0
	go.opentelemetry.io/collector v0.60.0
	go.opentelemetry.io/collector v0.60.0
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/lokiexporter v0.60.0
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter v0.60.0
	go.opentelemetry.io/collector v0.60.0
	go.opentelemetry.io/collector v0.60.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.60.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.60.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.60.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/lokiprocessor v0.60.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/metricstransformprocessor v0.60.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/nomadprocessor v0.60.0
	go.opentelemetry.io/collector v0.62.0
)

























replace github.com/open-telemetry/opentelemetry-collector-contrib/processor/lokiprocessor => ./processor/lokiprocessor
replace github.com/open-telemetry/opentelemetry-collector-contrib/processor/nomadprocessor => ./processor/nomadprocessor
replace github.com/open-telemetry/opentelemetry-collector-contrib/receiver/vaultkvreceiver => ./receiver/vaultkvreceiver
