// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for digitaloceanreceiver/account metrics.
type MetricsConfig struct {
	DigitaloceanAccountDropletLimit MetricConfig `mapstructure:"digitalocean.account.droplet_limit"`
	DigitaloceanAccountVolumeLimit  MetricConfig `mapstructure:"digitalocean.account.volume_limit"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		DigitaloceanAccountDropletLimit: MetricConfig{
			Enabled: true,
		},
		DigitaloceanAccountVolumeLimit: MetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for digitaloceanreceiver/account metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}
