# https://github.com/hashicorp/vault/pull/12358
VERSION 0.6
FROM golang:1.20
WORKDIR /bloominlabs-otel-collector

deps:
  RUN GO111MODULE=on go install go.opentelemetry.io/collector/cmd/builder@v0.74.0
  RUN GO111MODULE=on go install github.com/open-telemetry/opentelemetry-collector-contrib/cmd/mdatagen@v0.74.0

receiver:
  FROM ../../../bloominlabs-otel-collector+deps

  COPY . .
  RUN go generate ./...

  SAVE ARTIFACT . vaultkvreceiver
  SAVE ARTIFACT ./internal/metadata/ AS LOCAL ./internal/
