# https://github.com/hashicorp/vault/pull/12358
VERSION 0.6
FROM golang:1.20
WORKDIR /bloominlabs-otel-collector

receiver:
  FROM ../../../bloominlabs-otel-collector+deps

  COPY . .
  RUN go generate ./...

  SAVE ARTIFACT . digitaloceanreceiver
  SAVE ARTIFACT ./internal/ AS LOCAL ./internal/
