// Code generated by mdatagen. DO NOT EDIT.

package metadata

import "go.opentelemetry.io/collector/confmap"

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for digitaloceanreceiver/billing metrics.
type MetricsConfig struct {
	DigitaloceanBillingBalance     MetricConfig `mapstructure:"digitalocean.billing.balance"`
	DigitaloceanBillingGeneratedAt MetricConfig `mapstructure:"digitalocean.billing.generated_at"`
	DigitaloceanBillingUsage       MetricConfig `mapstructure:"digitalocean.billing.usage"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		DigitaloceanBillingBalance: MetricConfig{
			Enabled: true,
		},
		DigitaloceanBillingGeneratedAt: MetricConfig{
			Enabled: true,
		},
		DigitaloceanBillingUsage: MetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for digitaloceanreceiver/billing metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}
