# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: bloominlabs-otel-collector

on:
  push:
    branches: [main]
    tags:
      - "*"
  pull_request:
    branches: [main]

jobs:
  bloominlabs-otel-collector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install CA
        run: 'sudo sh -c "echo \"${{ secrets.VAULT_CA }}\" | base64 -d >> /usr/local/share/ca-certificates/internal.crt" && sudo update-ca-certificates'
      - name: Authenticate to Tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build bloominlabs-otel-collector
        if: github.event_name == 'pull_request'
        run: |
          earthly --ci +release
      - name: build bloominlabs-otel-collector (push)
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
        run: |
          # cannot use --ci since it implies --no-output which wouldn't allow the release 
          earthly --use-inline-cache --save-inline-cache --strict --push +release
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            ./bin/*.tar.gz
            ./bin/SHA256SUMS
