name: otel-collector

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EARTHLY_VERSION: v0.6.2
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions-setup@a32f779fcc0e1a31c422e60e1cbbe4f5f80b7679
      - name: Install CA
        run: 'sudo sh -c "echo \"${{ secrets.VAULT_CA }}\" | base64 -d >> /usr/local/share/ca-certificates/internal.crt" && sudo update-ca-certificates'
      - name: Authenticate to Tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: build otel-collector docker image
        run: |
          earthly --ci --push +docker
